language: python
python:
- 2.7
- 3.4
install:
- PACKAGE_VERSION=`python setup.py --version`
- TAG_NAME=v$PACKAGE_VERSION
- pip install .
- pip install -r requirements.txt
- pip install coveralls
before_install:
- export TRAVIS_COMMIT_MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
- echo "$TRAVIS_COMMIT_MESSAGE"
script:
- 'export NYNAB_LOGGINGLEVEL=debug;
  coverage run -m unittest discover tests;
  coverage run -m unittest discover test_sync;
  '
- ( if [ -n "$TRAVIS_TAG" ]; then if [ $TAG_NAME != $TRAVIS_TAG ]; then echo "This tag is for the wrong version. Got \"$TRAVIS_TAG\" expected \"$TAG_NAME\"."; exit 1; fi; fi; )
after_success:
- pip install coveralls
- coveralls
before_deploy:
# create the documentation
- pip install wheel
deploy:
  provider: pypi
  user: rienafairefr
  password:
    secure: WI3jOwC+gXEGgCc3Vet68uyJbmOTCvnpQ8q6xMLJyu7Q0+VgiaA8adEigiITqLwS5y+3C1wz0KYfxzoFt09fCaJwtUD9UoT6zC2H39xzK+sbCLAKiSKx2u29zCXV1f68hIkyFDjcdVdbqThoH6pOW3UwyR2OvmaeHKzj2kY3yrMPPq3diEpp091yqNJhJN+DuQq9Tolys+vG5CIXsWYV3Cczd+VDolc1yNOHYu43+vOsDt2XgPMvrqkc1R4BdHBmlL9keY+q9UUj9ZFVnFScBq7Lia8VB+/cqriduWbEePxmCZlN7SDV6ZyfvQahsS+G5RsR0DRvRm7wt5ZCgIG/VgYOQnlO42G53FmDzAZnNxyoFP7EuE+yr/+fgcMNoPoBVqEQ+OCbqyFclPqt5TQMH9dODdkbNdDR68idQpjuReb266oBnPaCow/pnn3TljtzYzYEiHFOZWR0xo4T6G67E2YCOfqvHwfR+dcHya+pKaL9y1ePyRkElXfYR+M6WsOLg00yjcoKRd5uzgexHYaKVeE/jObhL+0LOHwmULBkY7kM2IF3qtXAwRmpKsXLZX8RfCPmJe+4ARYmpJFKv1MG67Q3OnCgnE4AapVOSHfp+bSAi7XImmN6f/zZWyu68j+NS2/BbjIqfmkRraRiCupk4jUMcOUGAtHzrIFDMgmdOHA=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: rienafairefr/nYNABapi
